#!/usr/bin/env python3
"""
Demo script showing solidifai capabilities.

This script demonstrates the text-to-STL generation without requiring an OpenAI API key.
It shows the structure and flow of the application.
"""

import sys
from solidifai.generator import STLGenerator


def demo_without_api():
    """Demonstrate the structure without making actual API calls."""
    print("=" * 60)
    print("SOLIDIFAI - Text to STL Generator Demo")
    print("=" * 60)
    print()
    
    print("📝 How it works:")
    print("1. You provide a text description (e.g., 'a cube with 10mm sides')")
    print("2. OpenAI GPT-4 generates OpenSCAD code from your description")
    print("3. OpenSCAD compiles the code to an STL file")
    print("4. You get both .scad (editable) and .stl (printable) files")
    print()
    
    print("🔧 Example Usage:")
    print()
    print("  CLI Usage:")
    print("    $ solidifai 'a cube with 10mm sides' -o cube.stl")
    print()
    print("  Python API:")
    print("    from solidifai import STLGenerator")
    print("    generator = STLGenerator(api_key='your-key')")
    print("    generator.generate('a sphere with 15mm radius', 'sphere.stl')")
    print()
    
    print("📦 Example Descriptions:")
    descriptions = [
        "a simple cube with 20mm sides",
        "a cylinder with 15mm diameter and 30mm height",
        "a sphere with 25mm diameter",
        "an L-shaped bracket with 50mm legs and 5mm thickness",
        "a gear with 12 teeth and 30mm outer diameter",
        "a phone stand with 60 degree angle",
        "a cable organizer with 5 slots",
    ]
    
    for i, desc in enumerate(descriptions, 1):
        print(f"  {i}. {desc}")
    print()
    
    print("🚀 Getting Started:")
    print("1. Install: pip install -e .")
    print("2. Set API key: export OPENAI_API_KEY='your-key'")
    print("3. Run: solidifai 'your description' -o output.stl")
    print()
    
    print("📚 For more information, see README.md")
    print()


def show_code_example():
    """Show an example of generated OpenSCAD code."""
    print("=" * 60)
    print("Example OpenSCAD Code Generated by solidifai")
    print("=" * 60)
    print()
    print("Input: 'a cube with rounded corners, 20mm on each side'")
    print()
    print("Generated OpenSCAD Code:")
    print("-" * 60)
    
    example_code = """// Rounded cube
// 20mm on each side with 2mm corner radius

module rounded_cube(size, radius) {
    minkowski() {
        cube([size-2*radius, size-2*radius, size-2*radius], center=true);
        sphere(r=radius);
    }
}

// Create the rounded cube
rounded_cube(size=20, radius=2);
"""
    
    print(example_code)
    print("-" * 60)
    print()
    print("This code would then be compiled to an STL file!")
    print()


if __name__ == "__main__":
    demo_without_api()
    show_code_example()
    
    print("💡 Tip: Try it yourself by setting your OPENAI_API_KEY!")
    print()
